spring.application.name=social-post-backend

# Dynamic Port Binding for Cloud Hosting (Render / Docker / Local)
server.port=${PORT:8080}

# Data Source configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:socialdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Structured Logging configuration with Correlation ID
logging.level.com.himanshu.social_post_backend=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [trace=%X{correlationId}] --- [%15.15t] %-40.40logger{39} : %m%n

# Security & JWT Configuration (Exp 2.3.1)
security.jwt.secret=cu-fullstack2-himanshu-goyal-24bda70369-super-secure-jwt-secret-key-384bits
security.jwt.access-token-expiration-ms=900000
security.jwt.refresh-token-expiration-ms=604800000

# AES-256 Encryption Configuration (Exp 2.3.2)
security.aes.secret-key=cu-himanshu-aes256-key-32bytes!

# ===================================================================
# Apache Kafka & Reliability Configuration (Exp 3.1.1)
# ===================================================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=social-post-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Application-level Topic and Backoff Retry Configurations
app.kafka.topics.scheduled-posts=social-scheduled-posts
app.kafka.topics.scheduled-posts-dlq=social-scheduled-posts.DLT
app.kafka.retry.initial-interval-ms=300
app.kafka.retry.multiplier=2.0
app.kafka.retry.max-interval-ms=3000
app.kafka.retry.max-attempts=3


